version: '3.9'
services:
  odoo:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - '8069:8069'
    restart: on-failure

  db:
    image: postgres:13
    ports:
      - '5432:5432'
    restart: on-failure
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:5050'
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
