version: "3.9"
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    # volumes:
    #   - db_data:/var/lib/mysql
    environment:
      # MYSQL_USER: myuser
      # MYSQL_PASSWORD: mypass
      MYSQL_ROOT_PASSWORD: rootDB

# volumes:
#   db_data: