version: '3.9'
services:
  postgres:
    container_name: pg_container
    image: postgres:13
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: test_db
    logging:
      options:
        max-size: 10m
        max-file: '3'
    # volumes: 
      # - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
